<?php
/**
 * Magiccart
 * @Author: Martin Kovachev <miracle@nimasystems.com>
 * @var $block \Magiccart\Shopbrand\Block\Brand\Slider
 */

// NIMA CHANGES
?>
<?php

/** @var \Magiccart\Shopbrand\Block\Brand\Slider\Items $block */

$helper = $this->getHelper();
$brands = $block->getBrands();

if (!$brands->count()) {
    return;
}

?>
<div class="brands-slider-title">
    <a href="<?= $block->getUrl('shop-by-brand') ?>"><?= __('BRANDS') ?></a>
</div>

<div class="block brand-slider brand-slider-angro" style="margin-bottom: 30px;">
    <div class="block-content">
        <div data-owl="owl-slider">
            <div class="owl-carousel owl-theme">
                <?php foreach ($brands as $brand) :
                    $src = $block->getBrandImageUrl($brand);

                    if (!$src) {
                        continue;
                    }

                    ?>
                    <?php $href = $helper->getLinkBrand($brand); ?>
                    <div class="item">
                        <a title="<?= $block->escapeHtml($brand->getTitle()); ?>" href="<?= /* @escapeNotVerified */
                        $href ?>">
                            <img class="mark-lazy"
                                 width="100"
                                 height="100"
                                 src="<?= $src ?>"
                                 alt="<?= $block->escapeHtml($brand->getTitle()); ?>"
                            />
                        </a>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
