<?php
/**
 * Magiccart
 * @Author: Martin Kovachev <miracle@nimasystems.com>
 * @var $block \Magiccart\Shopbrand\Block\Brand\Slider
 */

/** @var \Magiccart\Shopbrand\Block\Brand\Slider $block */

$loadedOnVisible = true; //$block->isLoadedOnVisible();
$ajaxLoadUrl = $block->getBrandItemsUrl();

if ($loadedOnVisible) {
    ?>
    <?php $containerId = 'brand-slider-container-' . uniqid(); ?>
    <div class="block brand-slider-container" id="<?= $containerId ?>" data-ajax-url="<?= $ajaxLoadUrl ?>"></div>
    <script type="text/javascript">
        require(['jquery', 'brandsSlider'], function ($) {
            const container = document.getElementById('<?= $containerId ?>');
            $(container).brandsSlider();
        });
    </script>
    <?php
} else {
    ?>
<?php } ?>
